"""
Autodesk Inventor Workstation Agent (Port 8001)
Runs natively on Windows CAD Workstation (192.168.11.150).
Connects to live Autodesk Inventor application session via Windows COM.
Receives STEP models from the Text-to-CAD Workbench, converts them into native
.ipt (Part) or .iam (Assembly) models, and displays them live in Inventor.
"""

import os
import sys
import logging
import urllib.request
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

# Configure Logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("inventor_agent")

app = FastAPI(
    title="Autodesk Inventor Workstation Agent",
    description="High-speed COM automation bridge for Autodesk Inventor on 192.168.11.150",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Detect Windows COM environment
IS_WINDOWS = sys.platform.startswith("win")
win32com = None
pythoncom = None

if IS_WINDOWS:
    try:
        import win32com.client
        import pythoncom
        logger.info("win32com.client successfully loaded for Windows COM automation.")
    except ImportError:
        logger.warning("pywin32 not installed. Install with 'pip install pywin32'.")
else:
    logger.info("Running in non-Windows environment. COM calls will run in simulation mode.")


class OpenCadRequest(BaseModel):
    step_url: str = Field(..., description="HTTP URL to download the generated STEP file from the CAD Workbench")
    part_name: str = Field(default="model", description="Base file name for saving (without extension)")
    create_assembly: bool = Field(default=False, description="If True, creates a native .iam Assembly; if False, creates a .ipt Part")
    save_dir: Optional[str] = Field(default=None, description="Directory path on workstation to store .ipt/.iam files")
    bring_to_front: bool = Field(default=True, description="Bring Autodesk Inventor window to front")


class OpenCadResponse(BaseModel):
    success: bool
    message: str
    file_path: str
    file_type: str  # "Part (.ipt)" or "Assembly (.iam)"
    inventor_version: Optional[str] = None
    open_documents_count: int = 0


def get_default_save_dir() -> str:
    if IS_WINDOWS:
        user_profile = os.environ.get("USERPROFILE", "C:\\")
        target = os.path.join(user_profile, "Documents", "OmniCAD")
    else:
        target = os.path.expanduser("~/OmniCAD")
    os.makedirs(target, exist_ok=True)
    return target


def get_inventor_instance():
    """Connects to active Inventor application or launches a new instance."""
    if not IS_WINDOWS or win32com is None:
        return None

    pythoncom.CoInitialize()
    try:
        # Try connecting to already running Inventor session
        inv = win32com.client.GetActiveObject("Inventor.Application")
        logger.info("Connected to active Autodesk Inventor session.")
        return inv
    except Exception:
        logger.info("Inventor not currently open. Launching Inventor.Application...")
        try:
            inv = win32com.client.Dispatch("Inventor.Application")
            inv.Visible = True
            return inv
        except Exception as e:
            logger.error(f"Failed to launch Autodesk Inventor: {e}")
            raise HTTPException(
                status_code=503,
                detail=f"Autodesk Inventor is not running and could not be launched: {e}"
            )


@app.get("/health")
def health_check():
    """Reports workstation agent health and active Inventor session status."""
    inv_running = False
    inv_version = "Unknown"
    doc_count = 0

    if IS_WINDOWS and win32com is not None:
        try:
            pythoncom.CoInitialize()
            inv = win32com.client.GetActiveObject("Inventor.Application")
            inv_running = True
            inv_version = getattr(inv, "SoftwareVersion", {}).DisplayName if hasattr(inv, "SoftwareVersion") else "Running"
            doc_count = inv.Documents.Count
        except Exception:
            inv_running = False
    else:
        # Simulated mode for development/testing
        inv_running = True
        inv_version = "Simulated Inventor 2026"

    return {
        "status": "online",
        "workstation": "192.168.11.150",
        "inventor_connected": inv_running,
        "inventor_version": inv_version,
        "active_documents": doc_count,
        "platform": sys.platform
    }


@app.post("/api/inventor/open", response_model=OpenCadResponse)
def open_in_inventor(req: OpenCadRequest):
    """
    Downloads the STEP file generated by Text-to-CAD, converts it to a native
    Autodesk Inventor .ipt (Part) or .iam (Assembly), saves it, and focuses Inventor.
    """
    save_folder = req.save_dir or get_default_save_dir()
    os.makedirs(save_folder, exist_ok=True)

    sanitized_name = "".join(c for c in req.part_name if c.isalnum() or c in ("_", "-")).strip() or "model"
    local_step = os.path.join(save_folder, f"{sanitized_name}.step")

    # 1. Download STEP file from Workbench
    logger.info(f"Downloading STEP file from: {req.step_url}")
    try:
        urllib.request.urlretrieve(req.step_url, local_step)
        logger.info(f"STEP file successfully saved to: {local_step}")
    except Exception as e:
        logger.error(f"Failed downloading STEP file: {e}")
        raise HTTPException(status_code=400, detail=f"Could not retrieve STEP file from {req.step_url}: {e}")

    # 2. Non-Windows Simulation Fallback
    if not IS_WINDOWS or win32com is None:
        target_ext = ".iam" if req.create_assembly else ".ipt"
        sim_path = os.path.join(save_folder, f"{sanitized_name}{target_ext}")
        with open(sim_path, "w") as f:
            f.write(f"Simulated Inventor File: converted from {local_step}\n")
        
        return OpenCadResponse(
            success=True,
            message=f"Model converted and opened in Inventor (Simulated): {sim_path}",
            file_path=sim_path,
            file_type="Assembly (.iam)" if req.create_assembly else "Part (.ipt)",
            inventor_version="Simulated Inventor 2026",
            open_documents_count=1
        )

    # 3. Windows Native COM Automation
    inv = get_inventor_instance()
    inv_version = getattr(inv, "SoftwareVersion", {}).DisplayName if hasattr(inv, "SoftwareVersion") else "Inventor"

    try:
        # Open STEP in Inventor (Inventor auto-translates STEP into B-Rep geometry)
        logger.info(f"Opening STEP file in Inventor: {local_step}")
        doc = inv.Documents.Open(local_step)
        
        if req.create_assembly:
            # Save the translated part first
            ipt_path = os.path.join(save_folder, f"{sanitized_name}_part.ipt")
            doc.SaveAs(ipt_path, False)
            doc.Close(True)

            # Create an Assembly document (kAssemblyDocumentObject = 12291)
            asm_doc = inv.Documents.Add(12291, "", True)
            
            # Place the part occurrence at origin
            tg = inv.TransientGeometry
            matrix = tg.CreateMatrix()
            asm_doc.ComponentDefinition.Occurrences.Add(ipt_path, matrix)

            iam_path = os.path.join(save_folder, f"{sanitized_name}.iam")
            asm_doc.SaveAs(iam_path, False)

            if req.bring_to_front:
                inv.Visible = True
                inv.ActiveView.Fit()

            return OpenCadResponse(
                success=True,
                message=f"Created and opened native Autodesk Inventor Assembly (.iam)",
                file_path=iam_path,
                file_type="Assembly (.iam)",
                inventor_version=inv_version,
                open_documents_count=inv.Documents.Count
            )
        else:
            # Save directly as native Part (.ipt)
            ipt_path = os.path.join(save_folder, f"{sanitized_name}.ipt")
            doc.SaveAs(ipt_path, False)

            if req.bring_to_front:
                inv.Visible = True
                inv.ActiveView.Fit()

            return OpenCadResponse(
                success=True,
                message=f"Opened and saved native Autodesk Inventor Part (.ipt)",
                file_path=ipt_path,
                file_type="Part (.ipt)",
                inventor_version=inv_version,
                open_documents_count=inv.Documents.Count
            )

    except Exception as e:
        logger.error(f"Error during Inventor COM execution: {e}")
        raise HTTPException(
            status_code=500,
            detail=f"Autodesk Inventor execution failed: {e}"
        )


if __name__ == "__main__":
    port = int(os.getenv("INVENTOR_AGENT_PORT", 8001))
    logger.info(f"Starting Autodesk Inventor Workstation Agent on port {port}...")
    uvicorn.run(app, host="0.0.0.0", port=port)
